spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/todo_db?useSSL=false&characterEncoding=UTF-8


logging:
  level:
    org:
      hibernate:
        SQL: debug